### ISSUE TITLE
add azure spn as env vars from secret into the pipeline

### ISSUE THREAD

**Issue by nprashiyer** [nprashiyer/ado-ubuntu-agent#3]
```
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
```
